name: Deploy Notificion to VPS
 
on:
  push:
    branches: [ "main" ]
 
jobs:
  deploy:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
 
      - name: Copy project to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "."
          target: "~/Notificacion"
 
      - name: Deploy on VPS
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/Notificacion
            docker build -t mi-notificacion .
            docker stop mi-notificacion || true
            docker rm mi-notificacion || true
            docker run -d --name mi-notificacion -p 8091:8091 mi-notificacion
